export enum Race {
    Dragon = "Dragon",
    Warrior = "Warrior",
    Spellcaster = "Spellcaster",
    Fiend = "Fiend",
    Fairy = "Fairy",
    Zombie = "Zombie",
    Machine = "Machine",
    Aqua = "Aqua",
    Pyro = "Pyro",
    Rock = "Rock",
    WingedBeast = "Winged Beast",
    Plant = "Plant",
    Insect = "Insect",
    Thunder = "Thunder",
    Fish = "Fish",
    Dinosaur = "Dinosaur",
    Reptile = "Reptile",
    Psychic = "Psychic",
    DivineBeast = "Divine-Beast",
    Wyrm = "Wyrm",
    Cyberese = "Cyberese",
    Beast = "Beast",
    BeastWarrior = "Beast-Warrior",
    SeaSerpent = "Sea Serpent",
    Illusion = "Illusion"
}