export enum Type {
    Dragon = "Dragon",
    Spellcaster = "Spellcaster",
    Warrior = "Warrior",
    Fiend = "Fiend",
    Fairy = "Fairy",
    Beast = "Beast",
    Machine = "Machine",
    Aqua = "Aqua",
    Pyro = "Pyro",
    Rock = "Rock",
    Zombie = "Zombie",
    Insect = "Insect",
    Thunder = "Thunder",
    Plant = "Plant",
    Dinosaur = "Dinosaur",
    Fish = "Fish",
    WingedBeast = "Winged Beast",
    SeaSerpent = "Sea Serpent",
    Reptile = "Reptile",
    Psychic = "Psychic",
    DivineBeast = "Divine Beast",
    Illusion = "Illusion",
    BeastWarrior = "Beast-Warrior",
    Wyrm = "Wyrm",
    Cyberse = "Cyberse"
}